### ISSUE TITLE
Error reading/writing

### ISSUE THREAD

**Issue by romespud** [command-tab/ch341eeprom#5]
Hello!

I have a problem when reading/writing eeprom in ch341eeprom program.
Please help me.
[attach.zip](https://github.com/commandtab/ch341eeprom/files/231608/attach.zip)

In the attachment
original.bin - firmware in the chip.
read.bin - firmware read ch341eeprom
read.log - the output of  ./ch341eeprom -v -s 24c08 -d -r read.bin > read.log

**Comment by paolo-caroni** [comment]
Hi romespud,
reading and writing for chipset different to 24c32 and 24c64 are under development and with bug.
The original author of the project never implemented it, it's added by a de-comment the incomplete and bugged source since commit (https://github.com/commandtab/ch341eeprom/commit/7aad8e93bc98836cb7d53baef6e59b6e6634c9a6#diff-af9405206bb66f08e127908d895e514b).

However as you can see on the file ./wiresharkusbsniffing/sniffed.txt the "documentation" isn't complete.
If you have time and competence you can help on reverse engineering the windowsonlysoftware.
I have recently improved the mktestimg program for a better debugging, but I'm not a programmer, for me is only a hobby, and this for the moment is the better I can do.

Hope to be useful,
cheers,
Paolo

**Comment by paolo-caroni** [comment]
Hi romespud,
maybe you can try the patch/fork of plumbum (https://github.com/plumbum/ch341eeprom).
For me have correct the problem in reading on a 24c02 and probably can fix your problem.

Cheers,
Paolo

**Comment by romespud** [comment]
Problem solved. Thanks for the help.
